//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ditto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ditto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating directory: {0}.
        /// </summary>
        internal static string DirCreation {
            get {
                return ResourceManager.GetString("DirCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create directory {0}, path is too long..
        /// </summary>
        internal static string DirCreationLength {
            get {
                return ResourceManager.GetString("DirCreationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create directory {0}, access is denied..
        /// </summary>
        internal static string DirCreationUnauthorized {
            get {
                return ResourceManager.GetString("DirCreationUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create directory {0}, {1}.
        /// </summary>
        internal static string DirCreationUnknown {
            get {
                return ResourceManager.GetString("DirCreationUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting directory: {0}.
        /// </summary>
        internal static string DirDeletion {
            get {
                return ResourceManager.GetString("DirDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete directory {0}, directory in use, read-only or not empty..
        /// </summary>
        internal static string DirDeletionIOError {
            get {
                return ResourceManager.GetString("DirDeletionIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete directory {0}, path is too long..
        /// </summary>
        internal static string DirDeletionLength {
            get {
                return ResourceManager.GetString("DirDeletionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete directory, {0}, access is denied..
        /// </summary>
        internal static string DirDeletionUnauthorized {
            get {
                return ResourceManager.GetString("DirDeletionUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete directory {0}, {1}.
        /// </summary>
        internal static string DirDeletionUnknown {
            get {
                return ResourceManager.GetString("DirDeletionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Ditto {
            get {
                object obj = ResourceManager.GetObject("Ditto", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination:  {0} Folders, {1} Files, {2}.
        /// </summary>
        internal static string EmailDestination {
            get {
                return ResourceManager.GetString("EmailDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:         {0}.
        /// </summary>
        internal static string EmailFrom {
            get {
                return ResourceManager.GetString("EmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:       {0} Folders, {1} Files, {2}.
        /// </summary>
        internal static string EmailSource {
            get {
                return ResourceManager.GetString("EmailSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:           {0}.
        /// </summary>
        internal static string EmailTo {
            get {
                return ResourceManager.GetString("EmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file: {0}.
        /// </summary>
        internal static string FileCopy {
            get {
                return ResourceManager.GetString("FileCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy file {0}, directory not found..
        /// </summary>
        internal static string FileCopyDirNotFound {
            get {
                return ResourceManager.GetString("FileCopyDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy file {0}, source or destination is empty or contains invalid characters..
        /// </summary>
        internal static string FileCopyInvalidArg {
            get {
                return ResourceManager.GetString("FileCopyInvalidArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy file {0}, an I/O error occured..
        /// </summary>
        internal static string FileCopyIOError {
            get {
                return ResourceManager.GetString("FileCopyIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy file {0}, path is too long..
        /// </summary>
        internal static string FileCopyLength {
            get {
                return ResourceManager.GetString("FileCopyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy file {0}, access is denied..
        /// </summary>
        internal static string FileCopyUnauthorized {
            get {
                return ResourceManager.GetString("FileCopyUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy file {0}, {1}.
        /// </summary>
        internal static string FileCopyUnknown {
            get {
                return ResourceManager.GetString("FileCopyUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file: {0}.
        /// </summary>
        internal static string FileDeletion {
            get {
                return ResourceManager.GetString("FileDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete {0}, file is in use..
        /// </summary>
        internal static string FileDeletionIOError {
            get {
                return ResourceManager.GetString("FileDeletionIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete {0}, access is denied or file is read-only..
        /// </summary>
        internal static string FileDeletionUnauthorized {
            get {
                return ResourceManager.GetString("FileDeletionUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete {0}, {1}.
        /// </summary>
        internal static string FileDeletionUnknown {
            get {
                return ResourceManager.GetString("FileDeletionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is identical, skipping.
        /// </summary>
        internal static string FileSkip {
            get {
                return ResourceManager.GetString("FileSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:        {0} Created, {1} Deleted, {2} Updated, {3} Skipped, {4} Error(s).
        /// </summary>
        internal static string FileStats {
            get {
                return ResourceManager.GetString("FileStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating file: {0}.
        /// </summary>
        internal static string FileUpdate {
            get {
                return ResourceManager.GetString("FileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders:      {0} Created, {1} Deleted, {2} Skipped, {3} Error(s).
        /// </summary>
        internal static string FolderStats {
            get {
                return ResourceManager.GetString("FolderStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} B.
        /// </summary>
        internal static string SizeB {
            get {
                return ResourceManager.GetString("SizeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} EB.
        /// </summary>
        internal static string SizeEB {
            get {
                return ResourceManager.GetString("SizeEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} GB.
        /// </summary>
        internal static string SizeGB {
            get {
                return ResourceManager.GetString("SizeGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} KB.
        /// </summary>
        internal static string SizeKB {
            get {
                return ResourceManager.GetString("SizeKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} MB.
        /// </summary>
        internal static string SizeMB {
            get {
                return ResourceManager.GetString("SizeMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} PB.
        /// </summary>
        internal static string SizePB {
            get {
                return ResourceManager.GetString("SizePB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} TB.
        /// </summary>
        internal static string SizeTB {
            get {
                return ResourceManager.GetString("SizeTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} YB.
        /// </summary>
        internal static string SizeYB {
            get {
                return ResourceManager.GetString("SizeYB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} ZB.
        /// </summary>
        internal static string SizeZB {
            get {
                return ResourceManager.GetString("SizeZB", resourceCulture);
            }
        }
    }
}
